### ISSUE TITLE
Unable to run EF sample

### ISSUE THREAD

**Issue by this-fifo** [colombod/interactive-notebooks#1]
Hey @colombod , I apologize for adding an issue to this repo of yours, but I have been finding myself in dead ends looking at the existing Microsoft repositories for answers.

I'm looking to try running EF core on .NET Interactive within the vscode extension on a macOS environment.

Everything runs fine up to the creating the mssql kernel (although I don't seem to get a prompt about notifying me of a successful DbContext initialized in the C# Kernel, I get the same output of running the #!connect magic function without the --create-dbcontext param)

Next, when I try to run the C# code and do the Explore() piece, I get an error saying "The name 'adventureworksEF' does not exist in the current context".

Let me know if you can help somehow, I'm very interested in learning more about it.

I'm using the latest package from Nuget of Microsoft.DotNet.Interactive.SqlServer

**Comment by colombod** [comment]
Hello, better if you open this conversation over to the main repo (dotnet/interactive) and share a repro.We would be happy to look at the issue!Dr Diego Colombo PhDOn 17 Oct 2022, at 23:31, Filipe Herculano ***@***.***> wrote:﻿
Hey @colombod , I apologize for adding an issue to this repo of yours, but I have been finding myself in dead ends looking at the existing Microsoft repositories for answers.
I'm looking to try running EF core on .NET Interactive within the vscode extension on a macOS environment.
Everything runs fine up to the creating the mssql kernel (although I don't seem to get a prompt about notifying me of a successful DbContext initialized in the C# Kernel, I get the same output of running the #!connect magic function without the --create-dbcontext param)
Next, when I try to run the C# code and do the Explore() piece, I get an error saying "The name 'adventureworksEF' does not exist in the current context".
Let me know if you can help somehow, I'm very interested in learning more about it.
I'm using the latest package from Nuget of Microsoft.DotNet.Interactive.SqlServer

**Comment by this-fifo** [comment]
thank you for your time @colombod, I will do that then!

EDIT: here's the issue link https://github.com/dotnet/interactive/issues/2359
